return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "neovim/nvim-lspconfig",
  },
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup({
      ignore_install = {},
      modules = {},
      ensure_installed = {
        "printf",
        "lua",
        "luadoc",
        "vim",
        "vimdoc",
        "tmux",
        "query",
        "regex",
        "c",
        "cpp",
        "c_sharp",
        "go",
        "gomod",
        "markdown",
        "markdown_inline",
        "javascript",
        "jsdoc",
        "typescript",
        "tsx",
        "html",
        "css",
        "scss",
        "sql",
        "bash",
        "http",
        "proto",
        "dockerfile",
        "toml",
        "yaml",
        "xml",
        "json",
        "json5",
        "jsonc",
        "hjson",
        "jsonnet",
        "gitignore",
        "editorconfig",
      },
      sync_install = false,
      auto_install = true,
      highlight = {
        enable = true,
        use_languagetree = true,
        additional_vim_regex_highlighting = false,
      },
      indent = { enable = true },
    })
  end,
}
